spring.application.name=SatudentApplication
spring.datasource.url=jdbc:mysql://localhost/scdl
spring.datasource.username=root
spring.datasource.password=1207
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
